linux-yocto-meson32 5.2: Fix kernel build error
Add linux upstream patch to fix kernel build error dependency.

When compiling linux kernel using arch/arm/configs/multi_v7_defconfig it
generates the next error because of missing dependency:

| arm-poky-linux-gnueabi-ld.bfd: drivers/gpu/drm/rcar-du/rcar_lvds.o:(.rodata+0x4): undefined reference to `drm_atomic_helper_connector_reset'
| arm-poky-linux-gnueabi-ld.bfd: drivers/gpu/drm/rcar-du/rcar_lvds.o:(.rodata+0x10): undefined reference to `drm_helper_probe_single_connector_modes'
| arm-poky-linux-gnueabi-ld.bfd: drivers/gpu/drm/rcar-du/rcar_lvds.o:(.rodata+0x24): undefined reference to `drm_atomic_helper_connector_duplicate_state'
| arm-poky-linux-gnueabi-ld.bfd: drivers/gpu/drm/rcar-du/rcar_lvds.o:(.rodata+0x28): undefined reference to `drm_atomic_helper_connector_destroy_state'
| /workdir/build/tmp/work-shared/amlogic-s805/kernel-source/Makefile:1054: recipe for target 'vmlinux' failed
| make[1]: *** [vmlinux] Error 1
| /workdir/build/tmp/work-shared/amlogic-s805/kernel-source/Makefile:179: recipe for target 'sub-make' failed
| make: *** [sub-make] Error 2
| WARNING: exit code 1 from a shell command.
|
ERROR: Task (/workdir/poky/../meta-meson/recipes-kernel/linux/linux-yocto-meson32_5.2.bb:do_compile) failed with exit code '1'

Signed-off-by: Daniel Gomez <dagmcr@gmail.com>