s905-autoscript-multiboot: Fix conflict deployment
When building aml images for s9xxx machines the aml_autoscript is deployed
by 2 different recipes: s905-autoscript-multiboot and aml-autoscript.
Remove the generic one to avoid any conflict to fix this error:

ERROR: s905-autoscript-multiboot-1.0-r0 do_deploy_setscene: The recipe s905-autoscript-multiboot is trying to install files into a shared area when those files already exist. Those files and their manifest location are:
  /workdir/build/tmp/deploy/images/libretech-ac/aml_autoscript
    (matched in manifest-libretech_ac-aml-autoscript.deploy)
Please verify which recipe should provide the above files.

Signed-off-by: Daniel Gomez <dagmcr@gmail.com>