kernel-module-mali-utgard: Update driver to fix kernel build
Update mali-utgard driver to fix build error in kernel versions 5.3 and
greater:

| /workdir/build/tmp/work/libretech_ac-poky-linux/kernel-module-mali-utgard/r7p0-00rel1-meson-gx-r0/git/driver/src/devicedrv/mali/linux/mali_osk_time.c:57:9: error: implicit declaration of function 'ktime_get_boot_ns'; did you mean 'ktime_get_raw_ns'? [-Werror=implicit-function-declaration]
|    57 |  return ktime_get_boot_ns();
|       |         ^~~~~~~~~~~~~~~~~
|       |         ktime_get_raw_ns

Signed-off-by: Daniel Gomez <dagmcr@gmail.com>
(cherry picked from commit c7b53059b60473b5a1f582d97e752a275352bfae)