linux-meson64: fix perf build libbfd error
Linux kernel patch makes perf able to build with latest libbfd

Fixes:

| /workdir/build/tmp/work/libretech_ac-poky-linux/perf/1.0-r9/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.3.0/ld: /workdir/build/tmp/work/libretech_ac-poky-linux/perf/1.0-r9/perf-1.0/perf-in.o: in function `find_address_in_section':
| /usr/src/debug/perf/1.0-r9/perf-1.0/tools/perf/util/srcline.c:200: undefined reference to `bfd_get_section_flags'
| /workdir/build/tmp/work/libretech_ac-poky-linux/perf/1.0-r9/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.3.0/ld: /usr/src/debug/perf/1.0-r9/perf-1.0/tools/perf/util/srcline.c:204: undefined reference to `bfd_get_section_vma'
| /workdir/build/tmp/work/libretech_ac-poky-linux/perf/1.0-r9/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.3.0/ld: /usr/src/debug/perf/1.0-r9/perf-1.0/tools/perf/util/srcline.c:205: undefined reference to `bfd_get_section_size'

Signed-off-by: Daniel Gomez <dagmcr@gmail.com>
(cherry picked from commit 435336c8d78556b9318afb9b8e21be15aaa6a18e)